# FOSUser
fos_user:
    db_driver: orm
    firewall_name: principal
    user_class: App\Entity\Utilisateur
    from_email:
        address: "maintenance@lacouleurduzebre.com"
        sender_name: "maintenance@lacouleurduzebre.com"
    registration:
        confirmation:
            enabled: true