framework:
    default_locale: 'fr'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/themes/%theme%/translations'
        fallbacks:
            - 'fr'
