twig:
    paths: ['%kernel.project_dir%/public/themes/%theme%/templates', '%kernel.project_dir%/templates', '%kernel.project_dir%/src']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
