twig:
    paths: ['%kernel.project_dir%/themes/terresdoh/templates', '%kernel.project_dir%/templates', '%kernel.project_dir%/src/Modules']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
