Accordeon:
    priorite: 6
    actif: oui
Annuaire:
    priorite: 27
    actif: non
Bandeau:
    priorite: 2
    actif: oui
Bouton:
    priorite: 4
    actif: oui
Categorie:
    priorite: 13
    actif: oui
Formulaire:
    priorite: 9
    actif: oui
Galerie:
    priorite: 10
    actif: oui
Grille:
    priorite: 17
    actif: oui
GroupeBlocs:
    priorite: 16
    actif: oui
HTML:
    priorite: 22
    actif: oui
Image:
    priorite: 3
    actif: oui
LEI:
    priorite: 25
    actif: non
LogoSite:
    priorite: 21
    actif: oui
Menu:
    priorite: 19
    actif: oui
MenuLangues:
    priorite: 20
    actif: oui
Paragraphe:
    priorite: 1
    actif: oui
Partage:
    priorite: 15
    actif: oui
PlanDuSite:
    priorite: 24
    actif: oui
Recherche:
    priorite: 23
    actif: oui
ReseauxSociaux:
    priorite: 14
    actif: oui
Resume:
    priorite: 1
    actif: oui
Rubrique:
    priorite: 8
    actif: oui
Section:
    priorite: 5
    actif: oui
Slider:
    priorite: 7
    actif: oui
Template:
    priorite: 26
    actif: non
Texte:
    priorite: 11
    actif: oui
Titre:
    priorite: 2
    actif: oui
TypeCategorie:
    priorite: 18
    actif: oui
Video:
    priorite: 12
    actif: oui
Videos:
    priorite: 28
    actif: non
Vignette:
    priorite: 3
    actif: oui