easy_admin:
    entities:
        Categorie:
            class: App\Entity\Categorie
            controller: App\Controller\Back\AdminController
            label: 'Catégories'
            list:
                actions:
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                sort: 'nom'
                fields:
                    - nom
                    - { property: 'description', type: 'raw' }
                    - { property: 'url', type: 'text'}
                    - { property : 'categorieParent', label: 'Catégorie parent', sortable: true}
                    - { property : 'typeCategorie.nom', label: 'Type', sortable: true}
            search:
                sort: 'nom'
                fields:
                    - nom
                    - typeCategorie.nom
            show:
                fields:
                    - nom
                    - description
                    - url
                    - { property : 'categorieParent', label: 'Catégorie parent' }
                    - { property : 'typeCategorie.nom', label: 'Type'}
            form:
                actions:
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - langue
                    - description
                    - { property: 'url' }
                    - { property : 'categorieParent', label: 'Catégorie parent', type: 'entity', type_options: { class: 'App\Entity\Categorie' } }
                    - { property : 'typeCategorie', label: 'Type' }