easy_admin:
    entities:
        Configuration:
            class: App\Entity\Configuration
            controller: App\Controller\Back\AdminController
            disabled_actions: ['new', 'search', 'delete']
            list:
                fields:
                    - { property: 'logo', type: 'image' }
                    - { property: 'nom', label: 'Nom du site' }
                    - theme
                    - { property: 'editeur', label: 'Éditeur' }
                    - { property: 'langueDefaut', label: 'Langue par défaut' }
            form:
                actions:
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { property: 'nom', label: 'Nom du site' }
                    - { property: 'pageAccueil', label: "Page d'accueil" }
                    - { property: 'logo', type: 'text' }
                    #- { property: 'theme', label: 'Thème', type: 'App\Form\Type\ThemeType' }
                    - { property: 'metaDescription', label: 'Meta-description générale du site' }
                    - { property: 'editeur', label: 'Éditeur' }
                    - emailContact
                    - emailMaintenance
                    - { property: 'analytics', label: 'Clé Google Analytics' }
                    - { property: 'langueDefaut', label: 'Langue par défaut' }