easy_admin:
    entities:
        Configuration:
            class: App\Entity\Configuration
            controller: App\Controller\Back\AdminController
            disabled_actions: ['new', 'search', 'delete']
            list:
                fields:
                    - { property: 'logo', type: 'image' }
                    - { property: 'nom', label: 'Nom du site' }
                    - theme
                    - { property: 'editeur', label: 'Éditeur' }
                    - { property: 'langueDefaut', label: 'Langue par défaut' }
            form:
                actions:
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { property: 'nom', label: 'Nom du site' }
                    - { property: 'logo', type: 'text' }
                    - { property: 'editeur', label: 'Éditeur' }
                    - emailContact
                    - emailMaintenance
                    - { property: 'analytics', label: 'Script Google Analytics', type_options: { attr: { class: 'notTinymce' } } }
                    - { property: 'affichageCommentaires', label: 'Autoriser les commentaires sur les nouvelles pages' }
                    - { property: 'affichageDatePublication', label: 'Afficher la date de publication sur les nouvelles pages' }
                    - { property: 'maintenance', label: 'Mode maintenance', help: "Si le mode maintenance est activé, votre site ne sera pas accessible aux utilisateurs anonymes" }