easy_admin:
    entities:
        Configuration:
            class: App\Entity\Configuration
            controller: App\Controller\Back\AdminController
            disabled_actions: ['new', 'search', 'delete']
            list:
                fields:
                    - { property: 'logo', type: 'image', base_path: '/uploads' }
                    - { property: 'nom', label: 'Nom du site' }
                    - { property: 'url', type: 'url' }
                    - theme
                    - { property: 'editeur', label: 'Éditeur' }
                    - { property: 'langueDefaut', label: 'Langue par défaut' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom du site' }
                    - { property: 'url', type: 'text' }
                    - { property: 'logoFichier', type: 'vich_image', label: 'Logo' }
                    - { property: 'theme', label: 'Thème', type: 'App\Form\Type\ThemeType' }
                    - { property: 'editeur', label: 'Éditeur' }
                    - emailContact
                    - emailMaintenance
                    - emailNewsletter
                    - { property: 'analytics', label: 'Clé Google Analytics' }
                    - { property: 'langueDefaut', label: 'Langue par défaut' }