easy_admin:
    entities:
        GroupeBlocs:
            class: App\Entity\GroupeBlocs
            controller: App\Controller\Back\AdminController
            label: 'Groupe de blocs'
            labels: 'Groupes de blocs'
            list:
                fields:
                    - nom
                    - identifiant
                    - { property: 'region', label: 'Région'}
                    - langue
            search:
                fields:
                    - nom
                    - region
            show:
                fields:
                    - nom
                    - { property: 'region', label: 'Région'}
                    - blocs
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { type: 'tab', label: 'Contenus' }
                    - nom
                    - { property: 'blocs', type: 'collection', type_options: { entry_type: 'App\Form\Type\BlocType', by_reference: false } }
                    - { type: 'tab', label: 'Paramètres' }
                    - langue
                    - identifiant
                    - region
                    - position
            edit:
                title: nom