easy_admin:
    entities:
        Langue:
            class: App\Entity\Langue
            controller: App\Controller\Back\AdminController
            label: 'Langues'
            list:
                sort: 'abreviation'
                fields:
                    - nom
                    - abreviation
                    - active
                    - defaut
            search:
                sort: 'abreviation'
                fields:
                    - nom
            show:
                fields:
                    - abreviation
                    - nom
                    - active
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - abreviation
                    - { property: 'code', label: 'Code de la langue sous la forme xx-XX' }
                    - { property: 'metaTitre', label: 'Meta-titre général pour cette langue' }
                    - { property: 'metaDescription', label: 'Meta-description générale pour cette langue' }