easy_admin:
    entities:
        Langue:
            class: App\Entity\Langue
            controller: App\Controller\Back\AdminController
            label: 'Langues'
            list:
                sort: 'abreviation'
                fields:
                    - abreviation
                    - nom
                    - active
            search:
                sort: 'abreviation'
                fields:
                    - nom
            show:
                fields:
                    - abreviation
                    - nom
                    - active
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - abreviation
                    - active