easy_admin:
    entities:
        Menu:
            class: App\Entity\Menu
            controller: App\Controller\Back\AdminController
            label: 'Menu'
            labels: 'Menus'
            labelDeterminant: 'un menu'
            list:
                fields:
                    - nom
                    - langue
                    - { property: 'langue', label: 'Langue'}
                    - { property: 'defaut', label: 'Menu principal ?'}
            search:
                fields:
                    - nom
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - langue
            edit:
                title: nom
                fields:
                    - -langue