easy_admin:
    entities:
        Menu:
            class: App\Entity\Menu
            controller: App\Controller\Back\AdminController
            label: 'Menus'
            list:
                fields:
                    - nom
                    - { property: 'region', label: 'Région'}
            search:
                fields:
                    - nom
                    - region
            form:
                fields:
                    - nom
                    - { property: 'region', label: 'Région', type: 'App\Form\Type\RegionType' }
                    - { property: 'menuPage', label: 'Pages', type: 'collection', type_options: { entry_type: 'App\Form\Type\MenuPageType', by_reference: false } }