easy_admin:
    entities:
        Menu:
            class: App\Entity\Menu
            controller: App\Controller\Back\AdminController
            label: 'Menus'
            list:
                fields:
                    - nom
                    - { property: 'region', label: 'Région'}
                    - { property: 'defaut', label: 'Menu principal ?'}
            search:
                fields:
                    - nom
                    - region
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - { property: 'region', label: 'Région', type: 'App\Form\Type\RegionType' }
                    - { property: 'menuPage', label: 'Pages', type: 'collection', type_options: { entry_type: 'App\Form\Type\MenuPageType', by_reference: false } }