easy_admin:
    entities:
        Page_Active:
            class: App\Entity\Page
            controller: App\Controller\Back\AdminController
            label: 'Pages'
            disabled_actions: ['delete']
            list:
                dql_filter: 'entity.corbeille = false'
                sort: 'titre'
                actions:
                    - { name: 'edit', label: '', title: 'Éditer', icon: 'pencil-alt' }
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                    - { name: 'dupliquer', label: '', title: 'Dupliquer', icon: 'copy' }
                    - { name: 'corbeille', label: '', title: 'Mettre à la corbeille', icon: 'trash' }
                fields:
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories', type: 'array' }
                    - { property: 'dateCreation', label: 'Date de création' }
#                    - { property: 'datePublication', label: 'Date de publication' }
#                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - { property: 'seo.url', label: 'Url' }
                    - langue
                    - active
            search:
                title: 'Résultats de recherche'
                fields:
                    - titre
                    - auteur
                    - categories
            show:
                fields:
                    - titre
                    - contenu
                    - auteur
                    - auteurDerniereModification
                    - categories
                    - dateCreation
                    - { property: 'datePublication', label: 'Date de publication' }
                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - langue
                    - pageOriginale
                    - pagesTraduites
                    - commentaires
                    - seo
                    - active
            form:
                fields:
                    - { type: 'tab', label: 'Contenus' }
                    - { property: 'titre', type: 'text' }
                    - active
                    - corbeille
                    #- contenu
                    - { property: 'modules', type: 'collection', type_options: { entry_type: 'App\Form\Type\ModuleType', by_reference: false } }
                    - { type: 'tab', label: 'SEO' }
                    - { property: 'SEO', type: 'App\Form\Type\SEOType', type_options: { by_reference: true } }
                    #- image
                    - { type: 'tab', label: 'Catégories' }
                    - categories
                    - { type: 'tab', label: 'Historique' }
                    - datePublication
                    - dateDepublication
                    - { type: 'tab', label: 'Commentaires' }
                    - { property: 'commentaires', type: 'collection', type_options: { entry_type: 'App\Form\Type\CommentaireType', by_reference: false } }
                    - { type: 'tab', label: 'Traduction' }
                    - { property: 'langue', label: 'Page en :', nullable: false }
                    - { property: 'pageOriginale', label: 'Traduction de :'}
                    - { property: 'pagesTraduites', label: 'Page traduites :'}

        Page_Corbeille:
            class: App\Entity\Page
            label: 'Pages à la corbeille'
            list:
                dql_filter: 'entity.corbeille = true'
                sort: 'titre'
                actions:
                    - { name: 'corbeille', label: '', title: 'Restaurer', icon: 'recycle' }
                disabled_actions: ['edit', 'delete']
                fields:
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories' }
                    - { property: 'dateCreation', label: 'Date de création' }
                    - { property: 'seo.url', label: 'Url' }
                    - langue