easy_admin:
    entities:
        Page_Active:
            class: App\Entity\Page
            label: 'Pages'
            disabled_actions: ['delete']
            list:
                dql_filter: 'entity.corbeille = false'
                sort: 'titre'
                actions:
                    - { name: 'corbeille', label: '', title: 'Mettre à la corbeille', icon: 'trash' }
                fields:
                    - id
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories' }
                    - { property: 'dateCreation', label: 'Date de création' }
#                    - { property: 'datePublication', label: 'Date de publication' }
#                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - { property: 'seo.url', label: 'Url' }
                    - langue
                    - active
            search:
                fields:
                    - titre
                    - auteur
                    - categories
            show:
                fields:
                    - id
                    - titre
                    - contenu
                    - modules
                    - image
                    - auteur
                    - auteurDerniereModification
                    - categories
                    - dateCreation
                    - { property: 'datePublication', label: 'Date de publication' }
                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - pageParent
                    - langue
                    - pageOriginale
                    - pagesTraduites
                    - commentaires
                    - seo
                    - active
            form:
                fields:
                    - { type: 'tab', label: 'Contenus' }
                    - { property: 'titre', type: 'text' }
                    - contenu
                    #- { property: 'modules', type: 'collection', type_options: { entry_type: 'App\Form\Type\Modules\ModuleType', by_reference: true } }
                    #- image
                    - { type: 'tab', label: 'Historique' }
                    - datePublication
                    - dateDepublication
                    - { type: 'tab', label: 'Arborescence' }
                    - categories
                    - pageParent
                    #- { property: 'pageParent', type: 'App\Form\Type\PageParentType' }
                    - position
                    - active
                    - corbeille
                    - { type: 'tab', label: 'SEO' }
                    - { property: 'SEO', type: 'App\Form\Type\SEOType', type_options: { by_reference: true } }
                    - { type: 'tab', label: 'Commentaires' }
                    - { property: 'commentaires', type: 'collection', type_options: { entry_type: 'App\Form\Type\CommentaireType', by_reference: true } }
                    - { type: 'tab', label: 'Traduction' }
                    - langue
                    - pageOriginale
                    - pagesTraduites

        Page_Corbeille:
            class: App\Entity\Page
            label: 'Pages à la corbeille'
            list:
                dql_filter: 'entity.corbeille = true'
                sort: 'titre'
                actions:
                    - { name: 'corbeille', label: '', title: 'Restaurer', icon: 'recycle' }
                disabled_actions: ['edit', 'delete']
                fields:
                    - id
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories' }
                    - { property: 'dateCreation', label: 'Date de création' }
                    - { property: 'seo.url', label: 'Url' }
                    - langue