easy_admin:
    entities:
        Page_Active:
            class: App\Entity\Page
            controller: App\Controller\Back\Admin\PageAdminController
            label: 'Page'
            labels: 'Pages'
            disabled_actions: ['delete']
            list:
                dql_filter: 'entity.corbeille = false'
                sort: 'dateCreation'
                actions:
                    - { name: 'edit', label: '', title: 'Éditer', icon: 'pencil-alt' }
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                    - { name: 'dupliquer', label: '', title: 'Dupliquer', icon: 'copy' }
                    - { name: 'corbeille', label: '', title: 'Mettre à la corbeille', icon: 'trash' }
                fields:
                    - titre
                    - auteur
                    - { property: 'categories', label: 'Catégories' }
                    - { property: 'dateCreation', label: 'Date de création' }
                    - { property: 'datePublication', label: 'Date de publication' }
                    - langue
                    - active
            search:
                title: 'Résultats de recherche'
                fields:
                    - titre
                    - categories
                    - langue.nom
            show:
                fields:
                    - titre
                    - contenu
                    - auteur
                    - auteurDerniereModification
                    - categories
                    - dateCreation
                    - { property: 'datePublication', label: 'Date de publication' }
                    - { property: 'datedePublication', label: 'Date de dépublication' }
                    - langue
                    - pageOriginale
                    - pagesTraduites
                    - commentaires
                    - seo
                    - active
            form:
                actions:
                    - { name: 'dupliquer', label: 'Dupliquer', title: 'Dupliquer', icon: 'copy' }
                    - { name: 'corbeille', label: 'Mettre à la corbeille', title: 'Mettre à la corbeille', icon: 'trash' }
                    - { name: 'list', label: 'Retour à la liste des pages', title: 'Retour à la liste des pages', icon: 'arrow-left', css_class: '' }
                fields:
                    - { type: 'tab', label: 'Contenus' }
                    - { property: 'titre', type: 'text', type_options: { help: 'Utilisé en tant que balise H1 dans la page' } }
                    - { property: 'titreMenu', label: 'Titre dans les menus' }
                    - { property: 'blocs', type: 'collection', type_options: { entry_type: 'App\Form\Type\BlocType', by_reference: false } }
                    - { type: 'tab', label: 'Référencement' }
                    - { property: 'SEO', type: 'App\Form\Type\SEOType', type_options: { by_reference: true, label: false } }
                    - { type: 'tab', label: 'Affichage' }
                    - { type: 'group', label: 'Affichage des pages enfants', icon: 'file-alt' }
                    - { property: 'affichageSousNiveaux', label: 'Afficher les pages enfants dans les menus' }
                    - { type: 'group', label: 'Publication', icon: 'newspaper' }
                    - { property: 'affichageDatePublication', label: 'Afficher la date de publication' }
                    - datePublication
                    - dateDepublication
                    - { type: 'group', label: 'Auteur(s)', icon: 'feather-alt' }
                    - { property: 'affichageAuteur', label: "Afficher l'auteur" }
                    - { property: 'auteur', type_options: { disabled: true } }
                    - auteurDerniereModification
                    - { type: 'group', label: 'Blocs annexes', icon: 'shapes' }
                    - { property: 'blocsAnnexes', label: false, type: 'collection', type_options: { entry_type: 'App\Form\Type\BlocAnnexeType', by_reference: false } }
                    - { type: 'tab', label: 'Catégories' }
                    - { property: 'categories', type_options: { query_builder: 'App\Repository\CategorieRepository::orderByNom', group_by: 'typeCategorie' } }
                    - { type: 'tab', label: 'Commentaires' }
                    - { property: 'affichageCommentaires', label: 'Autoriser les commentaires' }
                    - { property: 'commentaires', type: 'collection', type_options: { entry_type: 'App\Form\Type\CommentaireType', by_reference: false } }
                    - { type: 'tab', label: 'Traduction' }
                    - { property: 'langue', label: 'Page en :', type_options: { required: true } }
                    - { property: 'traductions', label: 'Traductions :', type: 'App\Form\Type\TraductionsType' }
            edit:
                actions:
                    - { name: 'voir', label: 'Voir', title: 'Voir', icon: 'eye' }
                title: titre

        Page_Corbeille:
            class: App\Entity\Page
            controller: App\Controller\Back\Admin\PageAdminController
            label: 'Page à la corbeille'
            labels: 'Pages à la corbeille'
            disabled_actions: ['edit']
            list:
                dql_filter: 'entity.corbeille = true'
                sort: 'titre'
                actions:
                    - { name: 'corbeille', label: '', title: 'Restaurer', icon: 'recycle' }
                fields:
                    - titre
                    - auteur
                    - { property: 'dateCreation', label: 'Date de création' }
                    - { property: 'datePublication', label: 'Date de publication' }
                    - langue