easy_admin:
    entities:
        role:
            class: App\Entity\Role
            controller: App\Controller\Back\AdminController
            label: 'Rôle'
            labels: 'Rôles'
            disabled_actions: ['edit', 'search', 'show', 'list', 'new']