easy_admin:
    entities:
        SEO:
            class: App\Entity\SEO
            controller: App\Controller\Back\AdminController
            label: 'SEO'
            labels: 'SEO'
            disabled_actions: ['new', 'delete']
            list:
                actions:
                sort: ['url', 'ASC']
                fields:
                    - url
                    - metaTitre
                    - metaDescription
                    - page
            search:
                sort: ['url', 'ASC']
                fields:
                    - url
                    - metaTitre
                    - metaDescription
                    - page.titre
            form:
                actions:
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - url
                    - metaTitre
                    - metaDescription
            edit:
                title: page