easy_admin:
    entities:
        TypeCategorie:
            class: App\Entity\TypeCategorie
            controller: App\Controller\Back\AdminController
            label: 'Types de catégories'
            list:
                actions:
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                fields:
                    - nom
                    - { property: 'description', type: 'raw' }
                    - url
            search:
                fields:
                    - nom
                    - description
            show:
                fields:
                    - nom
                    - description
                    - url
            form:
                actions:
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - langue
                    - description
                    - url
