easy_admin:
    entities:
        TypeCategorie:
            class: App\Entity\TypeCategorie
            controller: App\Controller\Back\AdminController
            label: 'Types de catégories'
            list:
                fields:
                    - nom
                    - description
                    - url
            search:
                fields:
                    - nom
                    - description
            show:
                fields:
                    - nom
                    - description
                    - url
            form:
                fields:
                    - nom
                    - description
                    - url
