easy_admin:
    entities:
        Utilisateur:
            class: App\Entity\Utilisateur
            controller: App\Controller\Back\UtilisateurController
            label: 'Utilisateurs'
            list:
                fields:
                    - { property: 'imageProfil', type: 'image', base_path: '/uploads' }
                    - { property: 'username', label: 'Pseudonyme' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: 'Rôles' }
            search:
                fields:
                    - username
                    - email
            show:
                fields:
                    - { property: 'username', label: 'Pseudonyme' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: 'Rôles' }
            new:
                actions:
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { property: 'username', label: 'Pseudonyme' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'password', type: 'password', label: 'Mot de passe' }
                    - { property: 'imageProfilFichier', type: 'vich_image', label: 'Image de profil' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'roles', label: 'Rôles' }
            edit:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { property: 'username', label: 'Pseudonyme' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'imageProfilFichier', type: 'vich_image', label: 'Image de profil' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'roles', label: 'Rôles' }