easy_admin:
    entities:
        Zone:
            class: App\Entity\Zone
            label: 'Zones éditables'
            list:
                fields:
                    - id
                    - nom
                    - { property: 'region', label: 'Région'}
                    #- { property: 'contenu', type: 'raw' }
            search:
                fields:
                    - nom
                    - region
                    - contenu
            show:
                fields:
                    - id
                    - nom
                    - { property: 'region', label: 'Région'}
                    - { property: 'contenu', type: 'raw' }
            form:
                fields:
                    - nom
                    - { property: 'region', label: 'Région', type: 'App\Form\Type\RegionType' }
                    - contenu