easy_admin:
    entities:
        Zone:
            class: App\Entity\Zone
            controller: App\Controller\Back\AdminController
            label: 'Zones éditables'
            list:
                fields:
                    - nom
                    - { property: 'region', label: 'Région'}
                    #- { property: 'contenu', type: 'raw' }
            search:
                fields:
                    - nom
                    - region
                    - contenu
            show:
                fields:
                    - nom
                    - { property: 'region', label: 'Région'}
                    - { property: 'contenu', type: 'raw' }
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - { property: 'region', label: 'Région', type: 'App\Form\Type\RegionType' }
                    - { property: 'position', label: 'Ordre' }
                    - contenu